// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVptrK3gEDkz0yHY7nqHlLx67j_2HKSE',
    appId: '1:407225535957:web:74962499faf2487e9c415c',
    messagingSenderId: '407225535957',
    projectId: 'goal-diggers-c62ca',
    authDomain: 'goal-diggers-c62ca.firebaseapp.com',
    storageBucket: 'goal-diggers-c62ca.firebasestorage.app',
    measurementId: 'G-JGH327WXM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf99ggmeCJNuenTCFE-fD5IoecAtjsHH8',
    appId: '1:407225535957:android:b49fc6bef42b179f9c415c',
    messagingSenderId: '407225535957',
    projectId: 'goal-diggers-c62ca',
    storageBucket: 'goal-diggers-c62ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTyAr1T24joLeNhV_GZpKkfH3vmlojGQ',
    appId: '1:407225535957:ios:13083628c0ab024d9c415c',
    messagingSenderId: '407225535957',
    projectId: 'goal-diggers-c62ca',
    storageBucket: 'goal-diggers-c62ca.firebasestorage.app',
    iosBundleId: 'com.example.goalDiggers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaTyAr1T24joLeNhV_GZpKkfH3vmlojGQ',
    appId: '1:407225535957:ios:13083628c0ab024d9c415c',
    messagingSenderId: '407225535957',
    projectId: 'goal-diggers-c62ca',
    storageBucket: 'goal-diggers-c62ca.firebasestorage.app',
    iosBundleId: 'com.example.goalDiggers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVptrK3gEDkz0yHY7nqHlLx67j_2HKSE',
    appId: '1:407225535957:web:5a6138dd01845f1f9c415c',
    messagingSenderId: '407225535957',
    projectId: 'goal-diggers-c62ca',
    authDomain: 'goal-diggers-c62ca.firebaseapp.com',
    storageBucket: 'goal-diggers-c62ca.firebasestorage.app',
    measurementId: 'G-LW2MF8BPH0',
  );
}
